### ISSUE TITLE
Support of django 1.7 migrations

### ISSUE THREAD

**Issue by nautilebleu** [stephenmuss/django-ios-notifications#58]
Hi, 

Is there any plan for supporting django 1.7 migrations, with, for example, this behavior: http://treyhunner.com/2014/03/migrating-to-django-1-dot-7/ ?

Regards

**Comment by hairychris** [comment]
Sorry to necro but this is still open and is now fixed by https://github.com/stephenmuss/django-ios-notifications/pull/72 vote to close.
