### ISSUE TITLE
django 1.7 issue with ModelForm

### ISSUE THREAD

**Issue by kalvish21** [stephenmuss/django-ios-notifications#63]
I'm getting the following warnings after updating to latest version of Django:

    /Users/git/ios_notifications/forms.py:10: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form DeviceForm needs updating
    class DeviceForm(forms.ModelForm):

    /Users/git/ios_notifications/forms.py:15: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form APNServiceForm needs updating
    class APNServiceForm(forms.ModelForm):

    pydev debugger: process 18452 is connecting

    /Users/git/ios_notifications/forms.py:10: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form DeviceForm needs updating
    class DeviceForm(forms.ModelForm):

    /Users/git/ios_notifications/forms.py:15: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form APNServiceForm needs updating
    class APNServiceForm(forms.ModelForm):

Are there any updates for this i'm not aware of?

**Comment by stnatic** [comment]
Hi,

This PR should fix the issue:
https://github.com/stephenmuss/django-ios-notifications/pull/64

**Comment by stephenmuss** [comment]
Merged in 13859334e6641f884924daf664a80fb7da992bd1
