### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'is_active'

### ISSUE THREAD

**Issue by elliotbd** [stephenmuss/django-ios-notifications#67]
I get the following error when trying to send a notification:

  File "/kunden/homepages/12/d197654423/htdocs/manitouincline/leaderboard/manitouincline/manitouincline/views/climbs.py", line 525, in send_notifications
    service.push_notification_to_devices(notification, deviceToken, chunk_size=200)
  File "/homepages/12/d197654423/htdocs/manitouincline/leaderboard/lib/python2.7/site-packages/ios_notifications/models.py", line 110, in push_notification_to_devices
    self._write_message(notification, devices, chunk_size)
  File "/homepages/12/d197654423/htdocs/manitouincline/leaderboard/lib/python2.7/site-packages/ios_notifications/models.py", line 135, in _write_message
    if not device.is_active:
AttributeError: 'unicode' object has no attribute 'is_active'

Here is the code that calls push_notification_to_devices:

                        try:
                                service = APNService.objects.get(pk=1)
                        except APNService.DoesNotExist:
                                logger.debug( "APNService with id %d does not exist", service_id)

                        notification = Notification(message=outgoingMessage,
                                                badge=1,
                                                service=service,
                                                sound='')

                        service.push_notification_to_devices(notification, deviceToken, chunk_size=200)

----------------------------
or this:
----------------------------

apns = APNService.objects.get(hostname='gateway.sandbox.push.apple.com', name='manitouincline-dev')
                        #notification = Notification.objects.create(message=outgoingMessage, service=apns)
                        #apns.push_notification_to_devices(notification, deviceToken, chunk_size=200)

----------------------------

Both calls give the same error.

But I am able to send notifications from the admin form just fine with the same token id.

**Comment by stephenmuss** [comment]
Your problem seems to be that you are providing `deviceToken` which is a unicode object to `push_notification_to_devices`.

This method expects a list of Device objects and not a device token. If you wish to send to all devices you can simply use `service.push_notification_to_devices(notification, chunk_size=200)`.

Otherwise use something like:

```python
devices = Device.objects.filter(...)
service.push_notification_to_devices(notification, devices, chunk_size=200)
```

**Comment by elliotbd** [comment]
You nailed it!! That was the problem! It is working great now. Also I was using a Device.objects.get(...) instead of a Device.objects.filter(..). THANKS SO MUCH!! I am loving this package!!
