### ISSUE TITLE
Converting .p12 certificates to .txt

### ISSUE THREAD

**Issue by albertolina** [stephenmuss/django-ios-notifications#76]
Hello, your app requires the Apple push certificate in .txt format, how do I convert the generated push certificate and key in the .txt file, I tried to convert them and insert them in the APNS service but when I try to send the notification your app is always raising the error: [('PEM routines', 'PEM_read_bio', 'no start line')]

Best

**Comment by stephenmuss** [comment]
You should be able to follow the steps here to convert p12 https://www.raywenderlich.com/123862/push-notifications-tutorial
